services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgredb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  frontend:
    build:
      context:
      dockerfile: Dockerfile.frontend
    ports:
      - 8080:8080
    environment:
      - BACKEND_PROTOCOL=http
      - BACKEND_HOST=localhost
      - BACKEND_PORT=8080